/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgtry;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Suenlie
 */

abstract class Character{
    int healthPoints;
    
    public Character(int healthPoints){
        this.healthPoints = healthPoints;
    }
    
    public int getHealthPoints(){
        return healthPoints;
    }
    
    public boolean isAlive(){
        if(healthPoints <= 0){
            return false;
        }
        else{
            return true;
        }
    }
    
    public void takeDamage(int damage){
        healthPoints-=damage;
        if(healthPoints < 0){
            healthPoints = 0;
        }
    }
}

class Bird extends Character{
    public Bird(int healthPoints){
        super(healthPoints);
    }
    
    public void allOutShot(Character target){
        int damage = 109;
        target.takeDamage(damage);
    }
    
    public void trumphCard(Character target){
        int damage = 129;
        target.takeDamage(damage);
    }
    
    public void eggBomb(Character target){
        int damage = 128;
        target.takeDamage(damage);
    }
    
    public void blackMail(Character target){
        int damage = 111;
        target.takeDamage(damage);
    }
}

class Beast extends Character{
    public Beast(int healthPoints){
        super(healthPoints);
    }
    
    public void singleCombat(Character target){
        int damage = 79;
        target.takeDamage(damage);
    }
    
    public void nutCracker(Character target){
        int damage = 119;
        target.takeDamage(damage);
    }
    
    public void nutThrow(Character target){
        int damage = 119;
        target.takeDamage(damage);
    }
    
    public void ivory(Character target){
        int damage = 59;
        target.takeDamage(damage);
    }
}

class Plant extends Character{
    public Plant(int healthPoints){
        super(healthPoints);
    }
    
    public void vegebite(Character target){
        int damage = 30;
        target.takeDamage(damage);
    }
    
    public void carrot(Character target){
        int damage = 59;
        target.takeDamage(damage);
    }
    
    public void pricklyTrap(Character target){
        int damage = 119;
        target.takeDamage(damage);
    }
    
    public void disguise(Character target){
        int damage = 19;
        target.takeDamage(damage);
    }
}

class Enemy extends Character{
    public Enemy(int healthPoints){
        super(healthPoints);
    }
    
    public void enemyAttack1(Character target){
        int damage = 89;
        target.takeDamage(damage);
    }
    
    public void enemyAttack2(Character target){
        int damage = 76;
        target.takeDamage(damage);
    }
    
    public void enemyAttack3(Character target){
        int damage = 81;
        target.takeDamage(damage);
    }
    
    public void enemyAttack4(Character target){
        int damage = 120;
        target.takeDamage(damage);
    }
}


public class game extends javax.swing.JFrame {

    /**
     * Creates new form game
     */
    public game() {
        initComponents();
        
        Bird bird = new Bird(320);
        int birdhealth = bird.getHealthPoints();
        birdhp.setText("Bird: "+birdhealth+" Hp");
        
        Enemy enemy = new Enemy(599);
        int enemyHealth = enemy.getHealthPoints();
        enemyhp.setText("Enemy: "+enemyHealth+" Hp");
        
        beasthp.setText("Beast: "+beastHealth+" hp");
        planthp.setText("Beast: "+plantHealth+" hp");
        
        energyCounter.setText("Energy: "+energy);
        
        
    }
    int energy = 3;
    int alloutshot = 0;
    int eggbomb = 0;
    int blackmail = 0;
    int trumphcard = 0;
    int singleCombat = 0;
    int ivory = 0;
    int nutCracker = 0;
    int nutThrow = 0;
    int carrot = 0;
    int disguise = 0;
    int vegebite = 0;
    int pricklyTrap = 0;
    Enemy enemy = new Enemy(599);
    int enemyHealth = enemy.getHealthPoints();
    Bird bird = new Bird(320);
    int birdHealth = bird.getHealthPoints();
    Beast beast = new Beast(360);
    int beastHealth = beast.getHealthPoints();
    Plant plant = new Plant(560);
    int plantHealth = plant.getHealthPoints();
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        birdPanel = new javax.swing.JPanel();
        btnbird1 = new javax.swing.JButton();
        btnbird2 = new javax.swing.JButton();
        btnbird3 = new javax.swing.JButton();
        btnbird4 = new javax.swing.JButton();
        beastPanel = new javax.swing.JPanel();
        btnbeast1 = new javax.swing.JButton();
        btnbeast2 = new javax.swing.JButton();
        btnbeast3 = new javax.swing.JButton();
        btnbeast4 = new javax.swing.JButton();
        plantPanel = new javax.swing.JPanel();
        plantbtn1 = new javax.swing.JButton();
        plantbtn2 = new javax.swing.JButton();
        plantbtn3 = new javax.swing.JButton();
        plantbtn4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        energyCounter = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        birdhp = new javax.swing.JLabel();
        planthp = new javax.swing.JLabel();
        beasthp = new javax.swing.JLabel();
        btnEndTurn = new javax.swing.JButton();
        enemyhp = new javax.swing.JLabel();
        enemyChecker = new javax.swing.JLabel();
        plantDied = new javax.swing.JLabel();
        beastDied = new javax.swing.JLabel();
        birdDied = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        birdPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Bird"));

        btnbird1.setText("1");
        btnbird1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbird1MouseClicked(evt);
            }
        });
        btnbird1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbird1ActionPerformed(evt);
            }
        });

        btnbird2.setText("2");
        btnbird2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbird2MouseClicked(evt);
            }
        });
        btnbird2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbird2ActionPerformed(evt);
            }
        });

        btnbird3.setText("3");
        btnbird3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbird3MouseClicked(evt);
            }
        });
        btnbird3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbird3ActionPerformed(evt);
            }
        });

        btnbird4.setText("4");
        btnbird4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbird4MouseClicked(evt);
            }
        });
        btnbird4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbird4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout birdPanelLayout = new javax.swing.GroupLayout(birdPanel);
        birdPanel.setLayout(birdPanelLayout);
        birdPanelLayout.setHorizontalGroup(
            birdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(birdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnbird1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbird2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbird3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbird4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        birdPanelLayout.setVerticalGroup(
            birdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(birdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(birdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbird1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnbird2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnbird3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnbird4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        beastPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Beast"));

        btnbeast1.setText("5");
        btnbeast1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbeast1MouseClicked(evt);
            }
        });
        btnbeast1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbeast1ActionPerformed(evt);
            }
        });

        btnbeast2.setText("6");
        btnbeast2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbeast2MouseClicked(evt);
            }
        });
        btnbeast2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbeast2ActionPerformed(evt);
            }
        });

        btnbeast3.setText("7");
        btnbeast3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbeast3MouseClicked(evt);
            }
        });
        btnbeast3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbeast3ActionPerformed(evt);
            }
        });

        btnbeast4.setText("8");
        btnbeast4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbeast4MouseClicked(evt);
            }
        });
        btnbeast4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbeast4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout beastPanelLayout = new javax.swing.GroupLayout(beastPanel);
        beastPanel.setLayout(beastPanelLayout);
        beastPanelLayout.setHorizontalGroup(
            beastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beastPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnbeast1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbeast2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbeast3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbeast4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        beastPanelLayout.setVerticalGroup(
            beastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beastPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(beastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbeast1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnbeast2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnbeast3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnbeast4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        plantPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Plant"));

        plantbtn1.setText("9");
        plantbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plantbtn1MouseClicked(evt);
            }
        });
        plantbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plantbtn1ActionPerformed(evt);
            }
        });

        plantbtn2.setText("1");
        plantbtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plantbtn2MouseClicked(evt);
            }
        });
        plantbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plantbtn2ActionPerformed(evt);
            }
        });

        plantbtn3.setText("2");
        plantbtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plantbtn3MouseClicked(evt);
            }
        });
        plantbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plantbtn3ActionPerformed(evt);
            }
        });

        plantbtn4.setText("3");
        plantbtn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plantbtn4MouseClicked(evt);
            }
        });
        plantbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plantbtn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plantPanelLayout = new javax.swing.GroupLayout(plantPanel);
        plantPanel.setLayout(plantPanelLayout);
        plantPanelLayout.setHorizontalGroup(
            plantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plantPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plantbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plantbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plantbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plantbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        plantPanelLayout.setVerticalGroup(
            plantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plantPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plantbtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(plantbtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plantbtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plantbtn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgtry/images/birdaxie (3).png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgtry/images/axie-full-transparent (1).png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgtry/images/plantaxie (1).png"))); // NOI18N

        energyCounter.setText("Energy: ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(energyCounter)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(energyCounter)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgtry/images/enemy1-removebg-preview (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        birdhp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        birdhp.setText("Bird: ");

        planthp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        planthp.setText("Plant: ");

        beasthp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        beasthp.setText("Beast: ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(birdhp)
                    .addComponent(planthp)
                    .addComponent(beasthp))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(birdhp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(beasthp)
                .addGap(18, 18, 18)
                .addComponent(planthp)
                .addContainerGap())
        );

        btnEndTurn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEndTurn.setText("End Turn");
        btnEndTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndTurnActionPerformed(evt);
            }
        });

        enemyhp.setBackground(new java.awt.Color(204, 204, 204));
        enemyhp.setOpaque(true);

        plantDied.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        plantDied.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        beastDied.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        beastDied.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        birdDied.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        birdDied.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(birdDied, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 23, Short.MAX_VALUE)
                                .addComponent(birdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(beastDied, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(beastPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enemyhp, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enemyChecker, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(plantDied, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnEndTurn)
                                .addGap(22, 22, 22))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(plantPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 66, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(enemyChecker, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enemyhp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEndTurn)
                        .addGap(33, 33, 33)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(plantDied, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(birdDied, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(beastDied, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(beastPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plantPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(birdPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbird1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbird1ActionPerformed
        // TODO add your handling code here:
        if(energy != 0){
            alloutshot = 1;
            energy--;
            energyCounter.setText("Energy: "+energy);
        }else{
            btnbird1.setEnabled(false);
        }
        
    }//GEN-LAST:event_btnbird1ActionPerformed

    private void btnEndTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndTurnActionPerformed
        // TODO add your handling code here:
        plantbtn4.setBackground(new Color(255,255,255));
        plantbtn3.setBackground(new Color(255,255,255));
        plantbtn2.setBackground(new Color(255,255,255));
        plantbtn1.setBackground(new Color(255,255,255));
        btnbird1.setBackground(new Color(255,255,255));
        btnbird2.setBackground(new Color(255,255,255));
        btnbird3.setBackground(new Color(255,255,255));
        btnbird4.setBackground(new Color(255,255,255));
        btnbeast1.setBackground(new Color(255,255,255));
        btnbeast2.setBackground(new Color(255,255,255));
        btnbeast3.setBackground(new Color(255,255,255));
        btnbeast4.setBackground(new Color(255,255,255));
        
        btnbird1.setEnabled(true);
        btnbird2.setEnabled(true);
        btnbird3.setEnabled(true);
        btnbird4.setEnabled(true);
        btnbeast1.setEnabled(true);
        btnbeast2.setEnabled(true);
        btnbeast3.setEnabled(true);
        btnbeast4.setEnabled(true);
        plantbtn1.setEnabled(true);
        plantbtn2.setEnabled(true);
        plantbtn3.setEnabled(true);
        plantbtn4.setEnabled(true);
        
        energy+=2;
        energyCounter.setText("Energy: "+energy);
        
        if(alloutshot == 1){
            bird.allOutShot(enemy);
            alloutshot = 0;
        }
        
        if(trumphcard == 1){
            bird.trumphCard(enemy);
            trumphcard = 0;
        }
        
        if(eggbomb == 1){
            bird.trumphCard(enemy);
            eggbomb = 0;
        }
        
        if(blackmail == 1){
            bird.trumphCard(enemy);
            blackmail = 0;
        }
        
        if(singleCombat == 1){
            beast.singleCombat(enemy);
            singleCombat = 0;
        }
        
        if(ivory == 1){
            beast.ivory(enemy);
            ivory = 0;
        }
        
        if(nutCracker == 1){
            beast.nutCracker(enemy);
            nutCracker = 0;
        }
        
        if(nutThrow == 1){
            beast.nutThrow(enemy);
            nutThrow = 0;
        }
        
        if(pricklyTrap == 1){
            plant.pricklyTrap(enemy);
            pricklyTrap = 0;
        }
        
        if(vegebite == 1){
            plant.vegebite(enemy);
            vegebite = 0;
        }
        
        if(disguise == 1){
            plant.disguise(enemy);
            disguise = 0;
        }
        
        if(carrot == 1){
            plant.carrot(enemy);
            carrot = 0;
        }
        
        
        
        
        if(plant.isAlive()){
            enemy.enemyAttack1(plant);
            enemy.enemyAttack2(plant);
            enemy.enemyAttack3(plant);
            enemy.enemyAttack4(plant);
            plantHealth = plant.getHealthPoints();
            planthp.setText("Plant: "+plantHealth+" hp");
        }else if(!plant.isAlive() && beast.isAlive()){
            enemy.enemyAttack1(beast);
            enemy.enemyAttack2(beast);
            enemy.enemyAttack3(beast);
            enemy.enemyAttack4(beast);
            beastHealth = beast.getHealthPoints();
            beasthp.setText("Beast: "+beastHealth+" hp");
        }
        else{
            enemy.enemyAttack1(bird);
            enemy.enemyAttack2(bird);
            enemy.enemyAttack3(bird);
            enemy.enemyAttack4(bird);
            birdHealth = bird.getHealthPoints();
            birdhp.setText("Bird: "+birdHealth+" hp");
        }
        
        enemyHealth = enemy.getHealthPoints();
        enemyhp.setText("Enemy: "+enemyHealth+" hp");
        
        if(!enemy.isAlive()){
            enemyChecker.setText("Enemy has died.");
            JOptionPane.showMessageDialog(null, "You defeated the first enemy", "CONGRATULATIONS", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        }
        
        if(!plant.isAlive()){
            plantbtn1.setEnabled( false );
            plantbtn2.setEnabled( false );
            plantbtn3.setEnabled( false );
            plantbtn4.setEnabled( false );
            plantDied.setText("Your plant died!");
        }
        
        if(!beast.isAlive()){
            btnbeast1.setEnabled( false );
            btnbeast2.setEnabled( false );
            btnbeast3.setEnabled( false );
            btnbeast4.setEnabled( false );
            beastDied.setText("Your beast died!");
            
        }
        
        if(!bird.isAlive()){
            btnbird1.setEnabled( false );
            btnbird2.setEnabled( false );
            btnbird3.setEnabled( false );
            btnbird4.setEnabled( false );
            birdDied.setText("Your bird died!");
            JOptionPane.showMessageDialog(null, "You lost", "FAILED", JOptionPane.WARNING_MESSAGE);
            this.setVisible(false);
        }
        
        
    }//GEN-LAST:event_btnEndTurnActionPerformed

    private void btnbird2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbird2ActionPerformed
        // TODO add your handling code here:
        if(energy != 0){
           eggbomb = 1;
           energy--;
           energyCounter.setText("Energy: "+energy);
        }else{
            btnbird2.setEnabled(false);
        }
        
        
    }//GEN-LAST:event_btnbird2ActionPerformed

    private void btnbird3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbird3ActionPerformed
        // TODO add your handling code here:
        if(energy != 0){
            blackmail = 1;
            energy--;
            energyCounter.setText("Energy: "+energy);
        }else{
            btnbird3.setEnabled(false);
        }
        
        
    }//GEN-LAST:event_btnbird3ActionPerformed

    private void btnbird4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbird4ActionPerformed
        // TODO add your handling code here:
        if(energy != 0){
            trumphcard = 1;
            energy--;
            energyCounter.setText("Energy: "+energy);
        }else{
            btnbird4.setEnabled(false);
        }
        
        
    }//GEN-LAST:event_btnbird4ActionPerformed

    private void btnbird1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbird1MouseClicked
        // TODO add your handling code here:
        btnbird1.setBackground(Color.red);
    }//GEN-LAST:event_btnbird1MouseClicked

    private void btnbird2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbird2MouseClicked
        // TODO add your handling code here:
        btnbird2.setBackground(Color.red);
    }//GEN-LAST:event_btnbird2MouseClicked

    private void btnbird3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbird3MouseClicked
        // TODO add your handling code here:
        btnbird3.setBackground(Color.red);
    }//GEN-LAST:event_btnbird3MouseClicked

    private void btnbird4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbird4MouseClicked
        // TODO add your handling code here:
        btnbird4.setBackground(Color.red);
    }//GEN-LAST:event_btnbird4MouseClicked

    private void btnbeast1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbeast1ActionPerformed
        // TODO add your handling code here:
        if(energy != 0){
            singleCombat = 1;
            energy--;
            energyCounter.setText("Energy: "+energy);
        }else{
            btnbeast1.setEnabled(false);
        }
        
    }//GEN-LAST:event_btnbeast1ActionPerformed

    private void btnbeast2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbeast2ActionPerformed
        // TODO add your handling code here:
        if(energy != 0){
            ivory = 1;
            energy--;
            energyCounter.setText("Energy: "+energy);
        }else{
            btnbeast2.setEnabled(false);
        }
        
    }//GEN-LAST:event_btnbeast2ActionPerformed

    private void btnbeast3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbeast3ActionPerformed
        // TODO add your handling code here:
        if(energy != 0){
            nutCracker = 1;
            energy--;
            energyCounter.setText("Energy: "+energy);
        }else{
            btnbeast3.setEnabled(false);
        }
        
    }//GEN-LAST:event_btnbeast3ActionPerformed

    private void btnbeast4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbeast4ActionPerformed
        // TODO add your handling code here:
        if(energy != 0){
            nutThrow = 1;
            energy--;
            energyCounter.setText("Energy: "+energy);
        }else{
            btnbeast4.setEnabled(false);
        }
        
    }//GEN-LAST:event_btnbeast4ActionPerformed

    private void btnbeast1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbeast1MouseClicked
        // TODO add your handling code here:
        btnbeast1.setBackground(Color.red);
    }//GEN-LAST:event_btnbeast1MouseClicked

    private void btnbeast2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbeast2MouseClicked
        // TODO add your handling code here:
        btnbeast2.setBackground(Color.red);
    }//GEN-LAST:event_btnbeast2MouseClicked

    private void btnbeast3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbeast3MouseClicked
        // TODO add your handling code here:
        btnbeast3.setBackground(Color.red);
    }//GEN-LAST:event_btnbeast3MouseClicked

    private void btnbeast4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbeast4MouseClicked
        // TODO add your handling code here:
        btnbeast4.setBackground(Color.red);
    }//GEN-LAST:event_btnbeast4MouseClicked

    private void plantbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantbtn1ActionPerformed
        // TODO add your handling code here:
        if(energy != 0){
            pricklyTrap = 1;
            energy--;
            energyCounter.setText("Energy: "+energy);
        }else{
            plantbtn1.setEnabled(false);
        }
        
    }//GEN-LAST:event_plantbtn1ActionPerformed

    private void plantbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantbtn2ActionPerformed
        // TODO add your handling code here:
        if(energy != 0){
            disguise = 1;
            energy--;
            energyCounter.setText("Energy: "+energy);
        }else{
            plantbtn2.setEnabled(false);
        }
        
    }//GEN-LAST:event_plantbtn2ActionPerformed

    private void plantbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantbtn3ActionPerformed
        // TODO add your handling code here:
        if(energy != 0){
            vegebite = 1;
            energy--;
            energyCounter.setText("Energy: "+energy);
        }else{
            plantbtn3.setEnabled(false);
        }
       
    }//GEN-LAST:event_plantbtn3ActionPerformed

    private void plantbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantbtn4ActionPerformed
        // TODO add your handling code here:
        if(energy != 0){
            carrot = 1;
            energy--;
            energyCounter.setText("Energy: "+energy);
        }else{
            plantbtn4.setEnabled(false);
        }
        
    }//GEN-LAST:event_plantbtn4ActionPerformed

    private void plantbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plantbtn1MouseClicked
        // TODO add your handling code here:
        plantbtn1.setBackground(Color.red);
    }//GEN-LAST:event_plantbtn1MouseClicked

    private void plantbtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plantbtn2MouseClicked
        // TODO add your handling code here:
        plantbtn2.setBackground(Color.red);
    }//GEN-LAST:event_plantbtn2MouseClicked

    private void plantbtn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plantbtn3MouseClicked
        // TODO add your handling code here:
        plantbtn3.setBackground(Color.red);
    }//GEN-LAST:event_plantbtn3MouseClicked

    private void plantbtn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plantbtn4MouseClicked
        // TODO add your handling code here:
        plantbtn4.setBackground(Color.red);
    }//GEN-LAST:event_plantbtn4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel beastDied;
    private javax.swing.JPanel beastPanel;
    private javax.swing.JLabel beasthp;
    private javax.swing.JLabel birdDied;
    private javax.swing.JPanel birdPanel;
    private javax.swing.JLabel birdhp;
    private javax.swing.JButton btnEndTurn;
    private javax.swing.JButton btnbeast1;
    private javax.swing.JButton btnbeast2;
    private javax.swing.JButton btnbeast3;
    private javax.swing.JButton btnbeast4;
    private javax.swing.JButton btnbird1;
    private javax.swing.JButton btnbird2;
    private javax.swing.JButton btnbird3;
    private javax.swing.JButton btnbird4;
    private javax.swing.JLabel enemyChecker;
    private javax.swing.JLabel enemyhp;
    private javax.swing.JLabel energyCounter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel plantDied;
    private javax.swing.JPanel plantPanel;
    private javax.swing.JButton plantbtn1;
    private javax.swing.JButton plantbtn2;
    private javax.swing.JButton plantbtn3;
    private javax.swing.JButton plantbtn4;
    private javax.swing.JLabel planthp;
    // End of variables declaration//GEN-END:variables

    private void allOutShot(Enemy enemy) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
